import { Link } from './link';

export const LINKS: Link[] = [
    { name: 'Reddit', url: 'https://reddit.com', category: 'Bored'},
    { name: '4chan', url: 'https://boards.4chan.org', category: 'Bored'},
    { name: 'Twitter', url: 'https://twitter.com', category: 'Bored'},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
    { name: '', url: '', category: ''},
]