import { Link } from './link';

export const LINKS: Link[] = [
    { name: 'Reddit', url: 'https://reddit.com', category: 'Bored'},
    { name: '4chan', url: 'https://boards.4chan.org', category: 'Bored'},
    { name: 'Twitter', url: 'https://twitter.com', category: 'Bored'},
    { name: 'MonkeyType', url: 'https://monkeytype.com', category: 'Bored'},
    { name: 'MangaDex', url: 'https://mangadex.org', category: 'Bored'},
    { name: 'Github', url: 'https://github.com', category: 'Productivity'},
    { name: 'Unifi Controller', url: 'https://unifi.ubnt.com', category: 'Productivity'},
    { name: 'AWS', url: 'https://aws.amazon.com', category: 'Productivity'},
    { name: 'Free Code Camp', url: 'https://freecodecamp.org', category: ''},
    { name: 'Hacker 101 CTF', url: 'https://www.hacker101.com', category: ''},
    { name: 'HackerOne', url: 'https://www.hackerone.com', category: ''},
    { name: 'Robinhood', url: 'https://robinhood.com', category: ''},
    { name: 'Coinbase', url: 'https://coinbase.com', category: ''},
    { name: 'Binance', url: 'https://binance.us', category: ''},
    { name: 'TD Ameritrade', url: 'https://tdameritrade.com', category: ''},
    { name: 'E-Trade', url: 'https://us.etrade.com', category: ''},
    { name: 'Hacker News', url: 'https://news.ycombinator.com', category: ''},
    { name: 'Ars Technica', url: 'https://arstechnica.com', category: ''},
    { name: 'The Verge', url: 'https://theverge.com', category: ''},
    { name: 'Polygon', url: 'https://polygon.com', category: ''},
    { name: 'Bleeping Computer', url: 'https://bleepingcomputer.com', category: ''},
    { name: 'Google News', url: 'https://news.google.com', category: ''},
    { name: 'Arch Wiki', url: 'https://wiki.archlinux.org', category: ''},
    { name: 'Wikipedia', url: 'https://www.wikipedia.org', category: ''},
    { name: 'Exploit Database', url: 'https://exploit-db.com', category: ''},
    { name: 'StackOverflow', url: 'https://stackoverflow.com', category: ''},
    { name: 'Mozilla Developer Network', url: 'https://developer.mozilla.org', category: ''},
    { name: 'Youtube', url: 'https://youtube.com', category: ''},
    { name: 'Twitch', url: 'https://twitch.tv', category: ''},
    { name: 'Crunchyroll', url: 'https://crunchyroll.com', category: ''},
    { name: 'Netflix', url: 'https://netflix.com', category: ''},
    { name: 'Hulu', url: 'https://hulu.com', category: ''},
    { name: 'Prime Video', url: 'https://www.amazon.com/Amazon-Video/b/?&node=2858778011', category: ''},
]
